# Generated by Django 5.1.3 on 2025-01-22 21:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_document',
            field=models.FileField(blank=True, help_text="Driver's license document", null=True, upload_to=accounts.models.user_document_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=accounts.models.user_profile_image_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicle_registration',
            field=models.FileField(blank=True, help_text='Vehicle registration document', null=True, upload_to=accounts.models.user_document_path),
        ),
    ]
