# Generated by Django 5.1.3 on 2025-01-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='login_successful',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='security_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
